---
name: Playing with GithHub Super-Linter.

on:
  push:
    branches: main

  pull_request:
    branches: main

  workflow_dispatch:

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false

      - name: creating the documentation.
        uses: ammaraskar/sphinx-action@master
        with:
           name: html-docs
           path: .

      - name: Run a Shell command
        run: echo -e "Hello Alham! from GitHub-Actions.\n" && pwd && ls
        shell: bash
